// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import '../styles/globals.css';

// export const metadata = {
//   title: 'Visa Finder Tool',
//   description: 'Find the right visa based on your profile',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-50 text-gray-800 font-sans">
//         <main className="min-h-screen p-6">{children}</main>
//       </body>
//     </html>
//   );
// }



export const metadata = {
  title: 'Visa Finder Tool',
  description: 'Find the right visa based on your profile',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-800 font-sans">
        <main className="min-h-screen p-6">{children}</main>
      </body>
    </html>
  );
}